sudo: required

language: bash

services:
    - docker

before_install:
    - docker info
    - docker version

install:
    - docker build -t centos7-systemd tests/centos/7/

script:
    - container_id=$(mktemp)
    - docker run --detach --privileged --name RHEL7-CIS -v $(pwd):/ansible -v /sys/fs/cgroup:/sys/fs/cgroup centos7-systemd

    - bash ./tests/centos_7.sh

after_script:
    - docker ps -a
    - docker logs centos7-systemd

    - docker exec -i -t RHEL7-CIS ansible-playbook -i "localhost," -c local /ansible/tests/test.yml --syntax-check
  # Test role idempotence.
    - idempotence=$(mktemp)
    - sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml | tee -a ${idempotence}
    - >
      tail ${idempotence}
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

after_success:
# Clean up
- 'sudo docker stop "$(cat ${container_id})"'
